package ccm

import (
	"errors"
	"regexp"
	"time"

	"github.com/akamai/AkamaiOPEN-edgegrid-golang/v12/pkg/edgegriderr"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

type (
	// CreateCertificateRequest represents the parameters for creating a new certificate.
	CreateCertificateRequest struct {
		ContractID string
		GroupID    string
		Body       CertificateRequest
	}

	// CreateCertificateResponse contains the response for a certificate creation request.
	CreateCertificateResponse struct {
		Certificate
		Quota
	}

	// GetCertificateRequest represents the parameters for retrieving a certificate.
	GetCertificateRequest struct {
		CertificateID string
	}

	// GetCertificateResponse contains the response for retrieving a certificate.
	GetCertificateResponse = Certificate

	// PatchCertificateRequest represents the parameters for patching a certificate.
	PatchCertificateRequest struct {
		// Certificate identifier on which to perform the desired operation.
		CertificateID string

		// Signed certificate PEM content.
		SignedCertificatePEM string

		// PEM content of trust chain.
		TrustChainPEM string

		// Name of the certificate. To reset the name to a default value, provide an empty string.
		CertificateName *string

		// Parameter to acknowledge warnings and retry certificate upload when the returned response
		// contains warnings for the uploaded certificate.
		AcknowledgeWarnings bool
	}

	// PatchCertificateResponse contains the response for patching a certificate.
	PatchCertificateResponse = Certificate

	// UpdateCertificateRequest represents the parameters for updating a certificate.
	UpdateCertificateRequest = Certificate

	// UpdateCertificateResponse contains the response for updating a certificate.
	UpdateCertificateResponse = Certificate

	// DeleteCertificateRequest represents the parameters for deleting a certificate.
	DeleteCertificateRequest struct {
		CertificateID string
	}

	// GetCertificateBindingsRequest represents the parameters for retrieving certificate bindings.
	GetCertificateBindingsRequest struct {
		CertificateID string
	}

	// GetCertificateBindingsResponse contains the bindings for a certificate.
	GetCertificateBindingsResponse struct {
		Bindings []CertificateBinding `json:"bindings"`
		Links    Links                `json:"links"`
	}

	// ListCertificatesRequest represents the parameters for listing certificates.
	ListCertificatesRequest struct {
		CertificateName   string
		CertificateStatus string
		CertificateType   string
		ContractID        string
		Domain            string
		ExpiringInDays    *int64
		GroupID           int64
		Issuer            string
		KeyType           string

		IncludeCertificateMaterials bool
		PageSize                    int64
		Page                        int64
		Sort                        string
	}

	// ListCertificatesResponse contains a list of certificates and metadata.
	ListCertificatesResponse struct {
		Certificates []Certificate `json:"certificates"`
		Links        Links         `json:"links"`
		Metadata     ListMetadata  `json:"metadata"`
	}

	// ListBindingsRequest represents the parameters for listing certificate bindings.
	ListBindingsRequest struct {
		CertificateType string
		ContractID      string
		Domain          string
		ExpiringInDays  *int64
		GroupID         int64
		Network         string

		PageSize int64
		Page     int64
		Sort     string
	}

	// ListBindingsResponse contains a list of certificate bindings.
	ListBindingsResponse struct {
		Bindings []CertificateBinding `json:"bindings"`
		Links    Links                `json:"links"`
	}

	// CertificateRequest contains the details for requesting a certificate.
	CertificateRequest struct {
		CertificateName *string  `json:"certificateName,omitempty"`
		CertificateType *string  `json:"certificateType,omitempty"`
		KeyType         string   `json:"keyType"`
		KeySize         int64    `json:"keySize"`
		SecureNetwork   string   `json:"secureNetwork"`
		SANs            []string `json:"sans"`
		Subject         *Subject `json:"subject,omitempty"`
	}

	// Certificate represents a certificate and its metadata.
	Certificate struct {
		// Account identifier associated with ContractID.
		AccountID string `json:"accountId,omitempty"`

		// Unique identifier assigned to the newly created CCM certificate.
		CertificateID string `json:"certificateId,omitempty"`

		// Name of the certificate. User provided, if not autogenerated by the system.
		CertificateName string `json:"certificateName"`

		// Status of the certificate.
		CertificateStatus string `json:"certificateStatus,omitempty"`

		// Certificate type. Defaults to THIRD_PARTY.
		CertificateType string `json:"certificateType,omitempty"`

		// Contract identifier.
		ContractID string `json:"contractId,omitempty"`

		// User who created the certificate.
		CreatedBy string `json:"createdBy,omitempty"`

		// Date the certificate was created in UTC.
		CreatedDate time.Time `json:"createdDate,omitempty"`

		// Date when CSR will expire.
		CSRExpirationDate time.Time `json:"csrExpirationDate,omitempty"`

		// CSR PEM content generated by Akamai for RSA key type.
		CSRPEM string `json:"csrPem,omitempty"`

		// Key size to use for CSR.
		KeySize string `json:"keySize,omitempty"`

		// Key type to use for CSR. Either RSA or ECDSA.
		KeyType string `json:"keyType,omitempty"`

		// User who last modified the certificate.
		ModifiedBy string `json:"modifiedBy,omitempty"`

		// Date the certificate was last updated.
		ModifiedDate time.Time `json:"modifiedDate,omitempty"`

		// List of SAN (Subject Alternative Name) domains.
		SANs []string `json:"sans,omitempty"`

		// Secure network type to use for the certificate.
		SecureNetwork string `json:"secureNetwork,omitempty"`

		// Issuer field of the signed certificate.
		SignedCertificateIssuer *string `json:"signedCertificateIssuer,omitempty"`

		// Expiration date of signed certificate.
		SignedCertificateNotValidAfterDate *time.Time `json:"signedCertificateNotValidAfterDate,omitempty"`

		// Date before which the signed certificate is not valid.
		SignedCertificateNotValidBeforeDate *time.Time `json:"signedCertificateNotValidBeforeDate,omitempty"`

		// Signed certificate PEM content uploaded by end user for RSA key type.
		SignedCertificatePEM *string `json:"signedCertificatePem"`

		// SHA-256 fingerprint of signed certificate.
		SignedCertificateSHA256Fingerprint *string `json:"signedCertificateSHA256Fingerprint,omitempty"`

		// Signed certificate serial number in hex format.
		SignedCertificateSerialNumber *string `json:"signedCertificateSerialNumber,omitempty"`

		// Provided subject with optional fields as applicable.
		Subject *Subject `json:"subject,omitempty"`

		// PEM content of Trust chain uploaded by end user.
		TrustChainPEM *string `json:"trustChainPem"`
	}

	// Subject contains the subject details for a certificate.
	Subject struct {
		// Fully qualified domain name (FQDN) or other name associated with the subject.
		CommonName *string `json:"commonName,omitempty"`

		// Legal name of the organization.
		Organization *string `json:"organization,omitempty"`

		// Two-letter ISO 3166 country code.
		Country *string `json:"country,omitempty"`

		// Full name of the state or province.
		State *string `json:"state,omitempty"`

		// City or locality name.
		Locality *string `json:"locality,omitempty"`
	}

	// CertificateBinding represents a binding between a certificate and a resource.
	CertificateBinding struct {
		ResourceType  string `json:"resourceType"`
		CertificateID string `json:"certificateId"`
		Hostname      string `json:"hostname"`
		Network       string `json:"network"`
		Active        bool   `json:"active"`
	}

	// Links contains pagination and navigation links.
	Links struct {
		Self     string  `json:"self"`
		Next     *string `json:"next"`
		Previous *string `json:"previous"`
	}

	// ListMetadata contains metadata for paginated lists.
	ListMetadata struct {
		TotalItems int64 `json:"totalItems"`
		TotalPages int64 `json:"totalPages"`
	}

	// Quota contains information about certificate quotas.
	Quota struct {
		CertificateLimitTotal     int64
		CertificateLimitRemaining int64
	}
)

// Validate validates PatchCertificateRequest.
func (r PatchCertificateRequest) Validate() error {
	return edgegriderr.ParseValidationErrors(validation.Errors{
		"CertificateID": validation.Validate(r.CertificateID, validation.Required),
		"CertificateName": validation.Validate(r.CertificateName,
			validation.Length(0, 270),
			validation.Match(regexp.MustCompile(`^[a-zA-Z0-9 .\-_]+$`)).
				Error("the input can only contain digits (1-9), letters (a-z, A-Z), spaces, hyphens, periods, and underscores.")),
		"required parameters": validation.Validate(nil, validation.By(func(any) error {
			if r.SignedCertificatePEM == "" && r.CertificateName == nil {
				return errors.New("at least one of SignedCertificatePEM or CertificateName must be provided")
			}
			return nil
		})),
	})
}
